/*
 *%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 *%									   %
 *%	Copyright (C) 1991, by WATCOM Systems Inc. All rights reserved.    %
 *%									   %
 *%     Permission is granted to anyone to use this example program for	   %
 *%     any purpose on any computer system, subject to the following	   %
 *%	restrictions:							   %
 *%									   %
 *%     1. This example is provided on an "as is" basis, without warranty. %
 *%	   You indemnify, hold harmless and defend WATCOM from and against %
 *%	   any claims or lawsuits, including attorney's, that arise or	   %
 *%	   result from the use or distribution of this example, or any     %
 *%	   modification thereof.					   %
 *%									   %
 *%     2. You may not remove, alter or suppress this notice from this	   %
 *%        example program or any modification thereof.			   %
 *%									   %
 *%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 *
 * MENU.H
 *
 */
#define	MENU_ABOUT		101
#define	MENU_WRAP_AROUND	102
#define	MENU_BOUNDED_EDGES	103

#define	MENU_PAUSE		201
#define	MENU_RESUME		202
#define MENU_FASTEST		203

#define	MENU_CLEAR		301
#define	MENU_RANDOM		302
#define	MENU_GRID  		303

#define	MENU_LOAD_BITMAP	401
#define	MENU_NEW_RULES		402

#define MENU_ROTATE_P90		501
#define MENU_ROTATE_M90		502
#define MENU_ROTATE_180		503
#define MENU_REFLECT_X		504
#define MENU_REFLECT_Y		505

#define MENU_SAVE       	601
#define MENU_LOAD       	602

#define MENU_SINGLE_STEP	701
#define MENU_SELECT		702
#define MENU_FLIP_PATTERNS	703

#define	MENU_PATTERN		1000

#define MAX_MENU_SIZE_X		50
#define MAX_MENU_SIZE_Y		50

#define MIN_MENU_SIZE_X		20
#define MIN_MENU_SIZE_Y		20
