/*
 *%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 *%									   %
 *%	Copyright (C) 1991, by WATCOM Systems Inc. All rights reserved.    %
 *%									   %
 *%     Permission is granted to anyone to use this example program for	   %
 *%     any purpose on any computer system, subject to the following	   %
 *%	restrictions:							   %
 *%									   %
 *%     1. This example is provided on an "as is" basis, without warranty. %
 *%	   You indemnify, hold harmless and defend WATCOM from and against %
 *%	   any claims or lawsuits, including attorney's, that arise or	   %
 *%	   result from the use or distribution of this example, or any     %
 *%	   modification thereof.					   %
 *%									   %
 *%     2. You may not remove, alter or suppress this notice from this	   %
 *%        example program or any modification thereof.			   %
 *%									   %
 *%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 *
 * RULES.H
 *
 */
#define BM_BIRTH_0       100
#define BM_BIRTH_1       101
#define BM_BIRTH_2       102
#define BM_BIRTH_3       103
#define BM_BIRTH_4       104
#define BM_BIRTH_5       105
#define BM_BIRTH_6       106
#define BM_BIRTH_7       107
#define BM_BIRTH_8       108
#define BM_DEATH_0       200
#define BM_DEATH_1       201
#define BM_DEATH_2       202
#define BM_DEATH_3       203
#define BM_DEATH_4       204
#define BM_DEATH_5       205
#define BM_DEATH_6       206
#define BM_DEATH_7       207
#define BM_DEATH_8       208
#define BM_DEATH_NEVER   209
#define IDCANCEL         2
#define IDOK             1

